@recharge_key=
@shopify_variant_id=

###
GET https://api.rechargeapps.com/subscriptions?shopify_variant_id={{shopify_variant_id}}
Content-Type: application/json
X-Recharge-Access-Token: {{recharge_key}}
