@recharge_key={{$dotenv RECHARGE_TOKEN}}
@customer_id=
###
GET https://api.rechargeapps.com/subscriptions?customer_id={{customer_id}}
Accept: application/json
Content-Type: application/json
X-Recharge-Access-Token: {{recharge_key}}
