@recharge_token={{$dotenv RECHARGE_TOKEN}}
@address_id={{$dotenv ADDRESS_ID}}
@purchase_item_ids=[293384211]
@date=2022-11-21

###
#
POST https://api.rechargeapps.com/addresses/{{address_id}}/charges/skip
Content-Type: application/json
X-Recharge-Version: 2021-11
X-Recharge-Access-Token: {{recharge_token}}

{
  "date": "{{date}}",
  "subscription_ids": {{purchase_item_ids}}
}
